/* =========================================================================
   BLINDZY WEBSITE — EDITABLE CONTENT
   =========================================================================

   This file holds the TEXT and IMAGE PATHS shown on the homepage.
   It does NOT control colours, fonts, spacing or layout — only content.

   If you are not a developer, please read:
       CLIENT-EDITING-GUIDE.md   (in the main project folder)
   before changing anything here. It explains, in plain language, exactly
   how to safely edit this file with Notepad (Windows) or TextEdit (Mac).

   THE GOLDEN RULE:
   Only change the text that sits BETWEEN quote marks " ... "
   Never delete a quote mark ", a comma , or a curly bracket { }
   ========================================================================= */

// -------------------------------------------------------------------------
// 1. HERO SECTION (the big banner at the very top of the homepage)
// -------------------------------------------------------------------------
// To change the HERO BACKGROUND PHOTO, you do NOT edit this file.
// Simply replace these two image files with your new photo, keeping the
// exact same file name:
//   public/images/hero/hero-bg.png   -> background shown on desktop/laptop
//   public/images/hero/hero-bg2.png  -> background shown on mobile phones
// See CLIENT-EDITING-GUIDE.md, section "Changing the hero background photo".

export const heroContent = {
  heading: "Installing Blinds Made Easy",
  paragraph:
    "Welcome to Blindzy, your trusted source for custom DIY window furnishings in Australia. Browse our wide range of affordable, high quality window furnishings, and follow our simple installation guides to effortlessly transform your home",
  primaryButtonText: "Get Free Samples",
  primaryButtonLink: "/samples",
  secondaryButtonText: "Learn More",
  secondaryButtonLink: "/about",
};

// The 4 small white "feature" cards on the right side of the hero banner
// (Free Delivery, 10 Years Warranty, Made in Australia, Install Yourself).
// To ADD a new card, copy one whole { ... } block below, paste it before
// the closing "]", and edit its text. To REMOVE a card, delete its whole
// { ... } block. To change an icon picture, replace the file at that path
// in the public/images/icon/ folder (keep the same file name), or point
// "icon" at a different file name that already exists in that folder.
export const heroFeatureBoxes = [
  {
    icon: "/images/icon/box.png",
    title: "Free Delivery",
    description:
      "Fast, reliable delivery across Australia straight from our factory to your home.",
  },
  {
    icon: "/images/icon/guarantee.png",
    title: "10 Years Warranty",
    description:
      "Premium quality window furnishings backed by a 10 year warranty for long-term peace of mind.",
  },
  {
    icon: "/images/icon/australia.png",
    title: "Made in Australia",
    description:
      "Proudly manufactured in Melbourne using high quality materials and expert craftsmanship.",
  },
  {
    icon: "/images/icon/diy.png",
    title: "Install Yourself",
    description: "Easy-to-install blinds and curtains with simple guides",
  },
];

// -------------------------------------------------------------------------
// 2. PRODUCT CARDS (Blinds / Curtains / Shutters section on the homepage)
// -------------------------------------------------------------------------
// To ADD a new product card (e.g. a 4th product), copy one whole { ... }
// block below, paste it before the closing "]", and edit its text and
// image paths. To REMOVE a card, delete its whole { ... } block.
//
//   name            -> product title shown on the card
//   description     -> short sentence under the title
//   image           -> the product picture shown in the middle of the card
//   backgroundImage -> the photo that fades in when someone hovers the card
//   link            -> which page the card opens when clicked
//                       (must match a real page, e.g. "/shutters")
export const productsData = [
  {
    id: 1,
    name: "Blinds",
    description:
      "Sleek and versatile, offering a simple and stylish way to control light and privacy in any room.",
    image: "/images/product/blinds.png",
    backgroundImage: "/images/product/product1.jpg",
    link: "/blinds/roller-blinds",
  },
  {
    id: 2,
    name: "Curtains",
    description:
      "Offering a classic and elegant way to enhance privacy, control light, and add style to any room.",
    image: "/images/product/curtain.png",
    backgroundImage: "/images/product/product2.jpg",
    link: "/curtains",
  },
  {
    id: 3,
    name: "Shutters",
    description:
      "Plantation shutters are durable, louvered window coverings, designed to provide excellent light control, privacy, and a timeless, sophisticated look for any space.",
    image: "/images/product/shutters.png",
    backgroundImage: "/images/product/product3.jpg",
    link: "/shutters",
  },
];

// -------------------------------------------------------------------------
// 3. "WHY CHOOSE US?" SECTION (green rotating carousel of short reasons)
// -------------------------------------------------------------------------
export const whyChooseContent = {
  heading: "WHY CHOOSE US?",
  paragraph:
    "We invite you to join us on our mission to make home decorating fun and affordable for everyone. Explore our stunning collection of custom blinds and curtains today and experience the 5 Minute Blinds difference for yourself!",
};

// Each line in the carousel. Add or remove a line by adding/removing a
// whole "  \"...\"," entry below.
export const whyChooseReasons = [
  "Exceptional customer service and support.",
  "A diverse selection of stylish and trendy fabrics.",
  "Easy 5 minute installation.",
  "Family-owned with over 26 years of experience.",
  "Free shipping and a crazy 10 year warranty.",
];

// -------------------------------------------------------------------------
// 4. "HAVE ANY QUESTIONS?" SECTION
// -------------------------------------------------------------------------
export const questionsContent = {
  heading: "HAVE ANY QUESTIONS?",
  paragraph:
    "We'd love to hear from you! Whether it's measuring tips, installation advice, or product info, the Blindzy team is ready to help.",
  primaryButtonText: "Contact Us",
  primaryButtonLink: "/contact",
  secondaryButtonText: "Learn More",
  secondaryButtonLink: "/about",
};

// The 3 photo tiles (Shutters / Blinds / Curtains) inside that section.
export const questionsTiles = [
  { image: "/images/questions/1.png", label: "SHUTTERS", link: "/shutters" },
  { image: "/images/questions/2.png", label: "BLINDS", link: "/blinds/roller-blinds" },
  { image: "/images/questions/3.png", label: "CURTAINS", link: "/curtains" },
];

// -------------------------------------------------------------------------
// 5. "ABOUT US" SECTION
// -------------------------------------------------------------------------
export const aboutContent = {
  heading: "ABOUT US",
  paragraph:
    "At Blindzy, we believe that luxury is all about the details. That's why we take pride in offering premium blinds and curtains that combine craftsmanship with elegance. Based in Melbourne, Victoria, our state-of-the-art manufacturing facility ensures that every product we create is handmade and of the highest quality. As experts in window furnishings, our passion is reflected in every product we make.",
  buttonText: "Learn More",
  buttonLink: "/about",
  image: "/images/about/1.png",
};

// -------------------------------------------------------------------------
// 6. "WHAT OUR CLIENTS ARE SAYING" SECTION
// -------------------------------------------------------------------------
// NOTE: the individual customer reviews (name, star rating, review text)
// are NOT edited here — they come from the Strapi CMS admin panel.
// Only the section heading below is controlled by this file.
export const clientsContent = {
  heading: "What Our Clients are saying",
};
